import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

load_dotenv()


def create_pdf(content):
    """
    Creates a PDF file from text content.
    """
    file_name = "output.pdf"

    pdf = canvas.Canvas(file_name, pagesize=letter)

    y = 750
    for line in content.split("\n"):
        pdf.drawString(50, y, line)
        y -= 20

    pdf.save()

    return file_name


def create_text_file(content):
    """
    Creates a text file from content.
    """
    file_name = "output.txt"

    with open(file_name, "w", encoding="utf-8") as file:
        file.write(content)

    return file_name


import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv

load_dotenv()


def send_email(receiver_email, content, attachments=None):

    import os
    import smtplib
    from email.message import EmailMessage
    from dotenv import load_dotenv

    load_dotenv()

    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")

    msg = EmailMessage()

    msg["Subject"] = "Generated Content"
    msg["From"] = sender_email
    msg["To"] = receiver_email

    msg.set_content(content)

    if attachments:

        for file_path in attachments:

            if not os.path.exists(file_path):
                print(f"File not found: {file_path}")
                continue

            with open(file_path, "rb") as f:

                file_data = f.read()

                msg.add_attachment(
                    file_data,
                    maintype="application",
                    subtype="octet-stream",
                    filename=os.path.basename(file_path)
                )

    with smtplib.SMTP("smtp.gmail.com", 587) as server:

        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)

    return "Email sent successfully"

if __name__ == "__main__":
    content = """
    This is sample content generated by an LLM.
    It can be written to a PDF, text file,
    or sent through email.
    """

    create_pdf(content)
    create_text_file(content)

    # Uncomment and provide a valid email address
    # send_email("receiver@example.com", content)