import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

load_dotenv()


def create_pdf(content):
    """
    Creates a PDF file from text content.
    """
    file_name = "output.pdf"

    pdf = canvas.Canvas(file_name, pagesize=letter)

    y = 750
    for line in content.split("\n"):
        pdf.drawString(50, y, line)
        y -= 20

    pdf.save()

    return file_name


def create_text_file(content):
    """
    Creates a text file from content.
    """
    file_name = "output.txt"

    with open(file_name, "w", encoding="utf-8") as file:
        file.write(content)

    return file_name


def send_email(receiver_email, content):
    """
    Sends content as an email.
    Requires:
    SENDER_EMAIL and SENDER_PASSWORD in .env file
    """
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")

    msg = EmailMessage()
    msg["Subject"] = "Generated Content"
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg.set_content(content)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)

    return "Email sent successfully"


# Example Usage
if __name__ == "__main__":
    content = """
    This is sample content generated by an LLM.
    It can be written to a PDF, text file,
    or sent through email.
    """

    create_pdf(content)
    create_text_file(content)

    # Uncomment and provide a valid email address
    # send_email("receiver@example.com", content)